baseURL: "https://whaverals.github.io/whaverals.github.io"
title: "Wouter's Portfolio"
theme: "PaperMod"

params:
  env: production
  ShowReadingTime: true
  ShowPostNavLinks: true

markup:
  highlight:
    noClasses: false
