baseURL: "https://whaverals.github.io/"
title: "Wouter's Portfolio"
theme: "PaperMod"

params:
  env: production
  ShowReadingTime: false
  ShowPostNavLinks: true

markup:
  highlight:
    noClasses: false
